### PR TITLE
Changed comments

### PR DESCRIPTION
**Pull request by Thomas499**
Added to description so it was clear to user which list contained which sublist so that user didn't download the same list twice. Also added new whitelist containing common whitelisted items. Also took out descriptions of list that were not used i.e. b_moab and b_adzhosts.

Also reordered list so that master list was followed by the sub list that are included in the master. Also reordered list so that the ones most likely to give user problems are first and the ones user is most likely to keep are listed last. Also changed default to include steven black by default.

### CODE REVIEW

**Comment by kar** [comment]
@rpeter85 what do you think?

**Comment by rpeter85** [comment]
1.) I just checked the changes. Let me share my thoughts (so far):
In filter.properties, for Energized Basic, there is a statement "have a lot of RAM". What is "lot of RAM" now? Above 3 GB?

2.) Jerry's list: "Probably the cause of the problem if you have one". I would definitely get in touch with Jerry and talk with him before I make this sentence public.

3.) Can't see the point why Blu Go should be the default and not Blu. Earlier we decided to go with Blu to have a nice list that blocks most of the ads in most use cases, in **one** list. Go doesn't block that much and users may will face ads.
4.) Adding to the above, having 3 active lists instead of 1. It means, Blokada will download and merge them to filter out duplicates. Every time, based on users' "Download List Frequency". Isn't optimal.

5.) Energized Blu and Blu Go also marked as "recommended", however Blu is inactive by default (line 13 in filters.txt

6.) Energized Blu defined 2 times:
grep "b_energized_blu_name" api/v3/canonical/strings/filters.properties
b_energized_blu_name = Energized Blu (recommended)
b_energized_blu_name = Energized Blu

**Comment by rpeter85** [comment]
Additionally, I just run another grep and found that most of the Energized lists are defined 2 times:
cat api/v3/canonical/strings/filters.properties | awk '{ print $1 }' | sort | uniq -c | sort
...
...
   2 b_energized_blu_go_comment
   2 b_energized_blu_go_name
   2 b_energized_blu_name
   2 b_energized_spark_comment

**Comment by Thomas499** [comment]
> 1.) In filter.properties, for Energized Basic, there is a statement "have a lot of RAM". What is "lot of RAM" now? Above 3 GB? 

Should we just say "for high end devices" then? I know my phone (Kyocera) can't utilize the full list. Even the galaxy S4 can says it can only hold a max list size of about 400k, when no other apps are being used.

> 2.) Jerry's list: "Probably the cause of the problem if you have one". I would definitely get in touch with Jerry and talk with him before I make this sentence public.

I report most issues I find to Jerry. If the user runs into an issue, it is usually either from Jerrys list or occasionally energizer list. I see no reason to not tell users so on here rather than have them go to the chat form. Theres only like 6 topics that ever get brought up in the form and trying to debug which list is breaking their app is one of them. It is a fact that if user experiences issues, they should start debugging with Jerrys list first. 

> 3.) Can't see the point why Blu Go should be the default and not Blu. Earlier we decided to go with Blu to have a nice list that blocks most of the ads in most use cases, in one list. Go doesn't block that much and users may will face ads.

Alright we can keep Blu as default. 

> 4.) Adding to the above, having 3 active lists instead of 1. It means, Blokada will download and merge them to filter out duplicates. Every time, based on users' "Download List Frequency". Isn't optimal.

I strongly disagree with you on this one. Steven Blacks list are very good and have extremely low false positives. Most users elect multiple list anyway. 

I will correct 5 & 6 along with the second round comments you made. Lets make a decision for 1, 2, and 4. Can we vote on 2 and 4?

**Comment by rpeter85** [comment]
1.) Yes, that's better. Or "above X GB of RAM".
2.) I see no evidence for this. Most of the time not the lists cause issues, but DNS resolving, DNS availability, some kind of network setup. I don't accept this argument.
3.) Ok
4.) I'm curious for the stat you used to determine how much of the users use multiple lists :)
Other than that, my point is still valid: use 3 lists instead of 1, which also merges Steven Black's list. Why? You also saw the conversation about Blokada's startup time. The same would apply for every update as well: downloading 3 lists, then merging them.

**Comment by Thomas499** [comment]
1) Do you have a recommendation for what the "above X GB of RAM" should be listed as? 

2) If the reason for the issue is the list that are used I assure you its likely Jerrys. The first issue I noticed was with Jerrys list, you couldn't download any official apps on the firestick because mas-ext.amazon.com. This was documented here  https://github.com/jerryn70/GoodbyeAds/issues/13 and the only two list that included mas-ext.amazon.com were jerrys and energizer. Next, on the blokada form it was mentioned that blokada prevented the moovit app (transportation bus app) from being used. I looked into it and Jerrys list blocked app4.moovitapp.com static.moovitapp.com
and app4cdn.moovitapp.com which were all required for the app to work. This was documented here https://github.com/jerryn70/GoodbyeAds/issues/16 and only jerrys list blocked those sites. Next, the girlfriends parents bought a firestick from me and sent it to their daughter in Britain. Apparently, there is a British version of netflix called AcornTv app that wouldn't work. Turns out, api.rlje.net was required to be whitelisted on Jerrys list, and Energize list as documented here https://github.com/jerryn70/GoodbyeAds/issues/22. I've debugged a lot of apps not working and i'm telling you if there is an app that isn't working and you don't have the tools I have for debugging, you are best to start out with seeing if Jerrys list or energizer list is the problem. 

4.) Just ask on the chat form if people use more than one list. Most people use multiple list. Steven Blacks is solid. Whenever I am debugging which urls being blocked are the cause of a problem for list not working, if I see the url is included in steven blacks list I know it is legit. As far as start up time, the problem of start up time can be eliminated. I documented everything about this here https://github.com/blokadaorg/blokada/issues/403 with details on how to eliminate the start up time problem. If the list didn't re-download, then update, then repeat another 4 to 9 times it wouldn't be an issue. The problem is that the entire process happens multiple times. If you eliminate the issues I documented, then the process would only take 20-25% of the time it currently takes. Then you could easily download/upload 4 list in less time than it currently takes one list. Problem solved.

**Comment by Thomas499** [comment]
4. 
image see people want to use more than one list

**Comment by Thomas499** [comment]
Client feedback regarding the comment changes
image
image
image
image
image
At this point I was banned so had to continue conversation elsewhere
image
image
So from customer discovery (talking with client) we learned that this client wants multiple list enabled because he feels it will provide better protection from ads and tracking. It was not clear to him what list were overlapped, or why/if it was bad to enable all the list. Farther, we learned that the new commenting style added value in terms of clarity of which list overlapped. It is a shame that we can't verify this with 14 others who do not work on the project. Whoever blocked me from the telegram is a menace to progress.

**Comment by kar** [comment]
obsolete

**Pull request closed without merging**
